include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: false
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_collection_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_returning_null_for_void: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
    prefer_final_fields: true
    prefer_final_locals: true
